---
name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  HYPOTHESIS_PROFILE: "ci"
  UV_SYSTEM_PYTHON: "true"

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
        torch-version: ['2.1.0', '2.2.0', '2.3.0', '2.4.0']
    uses: ./.github/workflows/build-reusable.yml
    with:
      python-version: ${{ matrix.python-version }}
      torch-version: ${{ matrix.torch-version }}
      lint: ${{ matrix.python-version == '3.9' }}
